version: '3.9'

services:  
  backend:
    build: ./backend
    expose: 
      - 5000 
    ports:
      - "5000:5000"          
    depends_on:
       - frontend  # restart frontend with backend
        
  frontend:    
    build: ./frontend
    ports:        
      - "3000:3000"    
  